package UI;

import java.rmi.RemoteException; 



import javax.swing.JFrame;

import HotelUI.HotelFrame;
import NetworkManagersUI.NetworkManagersFrame;
import PO.hotelAccountPO;
import PO.hotelDataPO;
import PO.networkManageAccountPO;
import RMICLIENT.RMIClient;
import VO.hotelAccountVO;
import VO.hotelDataVO;
import VO.networkManageAccountVO;
import transform.POtoVO;
import transform.VOtoPO;
import UserUI.*;
import PO.userDataPO;
import PO.userAccountPO;
import VO.userAccountVO;
import VO.userDataVO;


/**
 *
 * @author User
 */
public class InputAccountFrame extends javax.swing.JFrame {

    /**
     * Creates new form InputAccountFrame
     */
    public InputAccountFrame(JFrame Login,int num) {
        typeNum = num;
        LoinFrame = Login;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        signUp = new javax.swing.JButton();
        login = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userIdJtext = new javax.swing.JTextField();
        passwordJPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(400, 300, 200, 100));

        signUp.setText("signup");
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					signUpActionPerformed(evt);
				} catch (RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        login.setText("login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        nameLabel.setText("用户名：");

        passwordLabel.setText("密码：");

        passwordJPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(signUp)
                        .addGap(37, 37, 37)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(cancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passwordJPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userIdJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(userIdJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLabel)
                    .addComponent(passwordJPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signUp)
                    .addComponent(login)
                    .addComponent(cancel))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        if(typeNum==3){
        	signUp.setVisible(false);
        }

        pack();
    }// </editor-fold>                        

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException {                                       
    	if(typeNum==1){     //用户注册
    		this.setVisible(false);
    		new UserUI.UserSignInFrame().setVisible(true);
    		
    		
    	}else if(typeNum==2){   //酒店注册
    		new hotelSignUpJFrame().setVisible(true);
    		
    		
    	}else{
    		
    		
    	}
    	
    	
    }                                      

    private void passwordJPasswordActionPerformed(java.awt.event.ActionEvent evt) {                                                  
       
    }                                                 

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {                                       
       this.setVisible(false);
    }                                      

    private void loginActionPerformed(java.awt.event.ActionEvent evt)  {        /*Login*/                              
    	
    	
		 
		 if(typeNum==1){ //客户端
			 userAccountPO accountPO = new userAccountPO();
			 userAccountVO accountVO = setUserAccount();
			 accountPO = vtp.TouserAccountPO(accountVO);
			 
			 
			 
			 try {
				if(RMIClient.getAccountService().userLogin(accountPO)&&!userIdJtext.getText().equals("")
						&&!passwordJPassword.getText().equals("")){
					 this.setVisible(false);
					 userDataPO dataPO = RMIClient.getBasicDataService().getUserData(accountPO.getUserID());
					 userDataVO dataVO = ptv.TouserDataVO(dataPO);
					 new UserMainFrame(dataVO).setVisible(true);
					
					
				 }
			} catch (RemoteException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			 
			 
			 
			 
			 
		 }else if(typeNum==2){ //酒店端
			 hotelAccountPO accountPO = new hotelAccountPO();
			 hotelAccountVO accountVO = setHotelAccount();
			 accountPO = vtp.ToHotelAccountPO(accountVO);
			 
			 
			 
			 try {
				if(RMIClient.getAccountService().hotelLogin(accountPO)&&!userIdJtext.getText().equals("")
						&&!passwordJPassword.getText().equals("")){
					 this.setVisible(false);
					 hotelDataPO dataPO = RMIClient.getBasicDataService().getHotelData(accountPO.getHotelID());
					 hotelDataVO dataVO = ptv.TOhotelDataVO(dataPO);
					 new HotelFrame(dataVO).setVisible(true);
					
					
				 }
			} catch (RemoteException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		 }else{ //网站管理人员端
			 networkManageAccountPO accountPO = new networkManageAccountPO();
			 networkManageAccountVO accountVO = setNetworkManageAccount();
			 accountPO = vtp.ToNetworkManageAccountPO(accountVO);
			 
			 
			 
			 try {
				if(RMIClient.getAccountService().networkManageLogin(accountPO)&&!userIdJtext.getText().equals("")
						&&!passwordJPassword.getText().equals("")){
					 this.setVisible(false);
					
					
					
				 }
			} catch (RemoteException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			 
		 }
		 
				 
		 LoinFrame.setVisible(false);
    }                                     
          
    /**
     * @param args the command line arguments
     */
  
    private hotelAccountVO setHotelAccount(){  //生成hotelAccountVO;
    	hotelAccountVO account = new hotelAccountVO(userIdJtext.getText(),passwordJPassword.getText());
    	return account;
    }
    
    private userAccountVO setUserAccount(){  //生成userAccountVO;
    	userAccountVO account = new userAccountVO(userIdJtext.getText(),passwordJPassword.getText());
    	return account;
    }
    
    private networkManageAccountVO setNetworkManageAccount(){  //生成hotelAccountVO;
    	networkManageAccountVO account = new networkManageAccountVO(userIdJtext.getText(),passwordJPassword.getText());
    	return account;
    }
    
    //还要写一个private userAccountVO setuserAccount()
    
    
    
    
 
    private int typeNum;
    private JFrame LoinFrame;
    private POtoVO ptv = new POtoVO();
    private VOtoPO vtp = new VOtoPO();
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton cancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordJPassword;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton signUp;
    private javax.swing.JTextField userIdJtext;
    // End of variables declaration                   
}
