package UI;

public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        loginUser = new javax.swing.JLabel();
        loginHotel = new javax.swing.JLabel();
        loginAdmin = new javax.swing.JLabel();
        LoginBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 300, 500, 400));
        setSize(new java.awt.Dimension(500, 400));

        BackGround.setBackground(new java.awt.Color(255, 255, 255));
        BackGround.setLayout(null);

        loginUser.setIcon(new javax.swing.ImageIcon("./大作业UI/UserLogin.png")); // NOI18N
        loginUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginUserMouseClicked(evt);
            }
        });
        BackGround.add(loginUser);
        loginUser.setBounds(60, 260, 140, 100);

        loginHotel.setIcon(new javax.swing.ImageIcon("./大作业UI/HotelLogin.png")); // NOI18N
        loginHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginHotelMouseClicked(evt);
            }
        });
        BackGround.add(loginHotel);
        loginHotel.setBounds(240, 260, 140, 100);

        loginAdmin.setIcon(new javax.swing.ImageIcon("./大作业UI/AdminLogin.png")); // NOI18N
        loginAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginAdminMouseClicked(evt);
            }
        });
        BackGround.add(loginAdmin);
        loginAdmin.setBounds(410, 260, 180, 100);

        LoginBackGround.setIcon(new javax.swing.ImageIcon("./大作业UI/LoginBackGround.png")); // NOI18N
        BackGround.add(LoginBackGround);
        LoginBackGround.setBounds(0, 0, 640, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        this.setVisible(true);
        
        pack();
    }// </editor-fold>                        

    private void loginUserMouseClicked(java.awt.event.MouseEvent evt) {                                       
        new InputAccountFrame(this,1).setVisible(true);//用户登录界面
    }                                      

    private void loginHotelMouseClicked(java.awt.event.MouseEvent evt) {                                        
        new InputAccountFrame(this,2).setVisible(true);//酒店登录界面
        
    }                                       

    private void loginAdminMouseClicked(java.awt.event.MouseEvent evt) {                                        
        new InputAccountFrame(this,3).setVisible(true);//网站管理登录界面
        
    }                                       

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify                     
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel LoginBackGround;
    private javax.swing.JLabel loginAdmin;
    private javax.swing.JLabel loginHotel;
    private javax.swing.JLabel loginUser;
    // End of variables declaration                   
}

