package HotelUI;

import java.rmi.RemoteException;
import java.util.ArrayList;

import PO.hotelPromotionPO;
import RMICLIENT.RMIClient;
import UI.LoginFrame;
import VO.hotelAccountVO;
import VO.hotelDataVO;



public class HotelFrame extends javax.swing.JFrame {

    /**
     * Creates new form HotelFrame
     */
    public HotelFrame(hotelDataVO data) {
        this.data = data;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        mainPanel = new javax.swing.JPanel();
        HotelInformationFrame = new javax.swing.JInternalFrame();
        hotelDataBGPanel = new javax.swing.JPanel();
        hotelAccountIcon = new javax.swing.JLabel();
        hotelName = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        back = new javax.swing.JButton();
        TelIcon = new javax.swing.JLabel();
        HotelTel = new javax.swing.JLabel();
        introductionIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        introduction = new javax.swing.JTextArea();
        hotelTelEdit = new javax.swing.JTextField();
        hotelNameEdit = new javax.swing.JTextField();
        modify = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        Hotelpart1 = new javax.swing.JPanel();
        HotelName = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Hotelpart2 = new javax.swing.JPanel();
        HotelOrder = new javax.swing.JLabel();
        userinformation = new javax.swing.JLabel();
        promotion = new javax.swing.JLabel();
        roomInformation = new javax.swing.JLabel();
        HotelOrder1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        UserLabel = new javax.swing.JLabel();
        orderLabel = new javax.swing.JLabel();
        promotionLabel = new javax.swing.JLabel();
        roomInformationLabel = new javax.swing.JLabel();
        updataLabel = new javax.swing.JLabel();
        HotelInformation = new javax.swing.JLabel();
        settingLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 300, 750, 500));
        setPreferredSize(new java.awt.Dimension(750, 480));
        setSize(new java.awt.Dimension(0, 0));

        mainPanel.setBackground(new java.awt.Color(39, 43, 48));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 440));
        mainPanel.setLayout(null);

        HotelInformationFrame.setBackground(new java.awt.Color(39, 43, 48));
        HotelInformationFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        HotelInformationFrame.setTitle("酒店信息");
        HotelInformationFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HotelInformationFrame.setVisible(false);

        hotelDataBGPanel.setBackground(new java.awt.Color(0, 76, 68));
        hotelDataBGPanel.setLayout(null);

        hotelAccountIcon.setIcon(new javax.swing.ImageIcon("./大作业UI/userData.png")); // NOI18N
        hotelDataBGPanel.add(hotelAccountIcon);
        hotelAccountIcon.setBounds(10, 10, 48, 48);

        hotelName.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        hotelName.setForeground(new java.awt.Color(51, 51, 255));
        hotelName.setText(data.getHotelName());
        hotelDataBGPanel.add(hotelName);
        hotelName.setBounds(70, 10, 280, 48);

        logout.setIcon(new javax.swing.ImageIcon("./大作业UI/Out.png")); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        hotelDataBGPanel.add(logout);
        logout.setBounds(506, 14, 46, 47);

        back.setIcon(new javax.swing.ImageIcon("./大作业UI/Prev.png")); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        hotelDataBGPanel.add(back);
        back.setBounds(455, 14, 47, 47);

        TelIcon.setIcon(new javax.swing.ImageIcon("./大作业UI/telephone_blue-55.png")); // NOI18N
        hotelDataBGPanel.add(TelIcon);
        TelIcon.setBounds(10, 80, 55, 55);

        HotelTel.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        HotelTel.setForeground(new java.awt.Color(51, 51, 255));
        HotelTel.setText(data.getHotelTel());
        hotelDataBGPanel.add(HotelTel);
        HotelTel.setBounds(70, 80, 280, 48);

        introductionIcon.setIcon(new javax.swing.ImageIcon("./大作业UI/introduction.png")); // NOI18N
        hotelDataBGPanel.add(introductionIcon);
        introductionIcon.setBounds(10, 160, 60, 51);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        introduction.setEditable(false);
        introduction.setBackground(new java.awt.Color(0, 76, 68));
        introduction.setColumns(20);
        introduction.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        introduction.setForeground(new java.awt.Color(51, 51, 255));
        introduction.setLineWrap(true);
        introduction.setRows(5);
        introduction.setText(data.getHotelIntroduction());
        jScrollPane1.setViewportView(introduction);

        hotelDataBGPanel.add(jScrollPane1);
        jScrollPane1.setBounds(70, 160, 280, 110);

        
        hotelTelEdit.setVisible(false);
        hotelTelEdit.setBackground(new java.awt.Color(0, 76, 68));
        hotelTelEdit.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        hotelTelEdit.setForeground(new java.awt.Color(51, 51, 255));
        hotelTelEdit.setText(data.getHotelTel());
        
        hotelTelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelTelEditActionPerformed(evt);
            }
        });
        hotelDataBGPanel.add(hotelTelEdit);
        hotelTelEdit.setBounds(70, 80, 280, 50);
        

        hotelNameEdit.setVisible(false);
        hotelNameEdit.setBackground(new java.awt.Color(0, 76, 68));
        hotelNameEdit.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        hotelNameEdit.setForeground(new java.awt.Color(51, 51, 255));
        hotelNameEdit.setText(data.getHotelName());
        hotelNameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelNameEditActionPerformed(evt);
            }
        });
        hotelDataBGPanel.add(hotelNameEdit);
        hotelNameEdit.setBounds(70, 10, 280, 50);
        

        modify.setIcon(new javax.swing.ImageIcon("./大作业UI/doc_edit_icon.png")); // NOI18N
        modify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyMouseClicked(evt);
            }
        });
        hotelDataBGPanel.add(modify);
        modify.setBounds(480, 210, 50, 50);

        save.setIcon(new javax.swing.ImageIcon("./大作业UI/checkbox_checked_icon.png")); // NOI18N
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        hotelDataBGPanel.add(save);
        save.setBounds(480, 210, 48, 50);
        save.setVisible(false);
        

        javax.swing.GroupLayout HotelInformationFrameLayout = new javax.swing.GroupLayout(HotelInformationFrame.getContentPane());
        HotelInformationFrame.getContentPane().setLayout(HotelInformationFrameLayout);
        HotelInformationFrameLayout.setHorizontalGroup(
            HotelInformationFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HotelInformationFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotelDataBGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HotelInformationFrameLayout.setVerticalGroup(
            HotelInformationFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HotelInformationFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotelDataBGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        mainPanel.add(HotelInformationFrame);
        HotelInformationFrame.setBounds(60, 50, 610, 370);

        Hotelpart1.setBackground(new java.awt.Color(0, 76, 68));
        Hotelpart1.setForeground(new java.awt.Color(102, 255, 255));
        Hotelpart1.setLayout(null);

        HotelName.setFont(new java.awt.Font("华文琥珀", 0, 36)); // NOI18N
        HotelName.setForeground(new java.awt.Color(204, 204, 159));
        HotelName.setText(data.getHotelName());
        Hotelpart1.add(HotelName);
        HotelName.setBounds(110, 40, 270, 38);

        backGround.setIcon(new javax.swing.ImageIcon("./大作业UI/beautifulPic.png")); // NOI18N
        Hotelpart1.add(backGround);
        backGround.setBounds(10, 10, 590, 90);
        Hotelpart1.add(jSeparator2);
        jSeparator2.setBounds(0, 0, 610, 10);

        mainPanel.add(Hotelpart1);
        Hotelpart1.setBounds(60, 30, 610, 110);

        Hotelpart2.setBackground(new java.awt.Color(0, 76, 68));
        Hotelpart2.setForeground(new java.awt.Color(255, 51, 51));

        HotelOrder.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        HotelOrder.setIcon(new javax.swing.ImageIcon("./大作业UI/order.png")); // NOI18N
        HotelOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HotelOrderMouseClicked(evt);
            }
        });

        userinformation.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        userinformation.setIcon(new javax.swing.ImageIcon("./大作业UI/userData.png")); // NOI18N
        userinformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userinformationMouseClicked(evt);
            }
        });

        promotion.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        promotion.setIcon(new javax.swing.ImageIcon("./大作业UI/sale.png")); // NOI18N
        promotion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                promotionMouseClicked(evt);
            }
        });

        roomInformation.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        roomInformation.setIcon(new javax.swing.ImageIcon("./大作业UI/room.png")); // NOI18N

        HotelOrder1.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        HotelOrder1.setIcon(new javax.swing.ImageIcon("./大作业UI/updata.png")); // NOI18N

        UserLabel.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserLabel.setText("用户信息");

        orderLabel.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        orderLabel.setForeground(new java.awt.Color(255, 255, 255));
        orderLabel.setText("我的订单");

        promotionLabel.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        promotionLabel.setForeground(new java.awt.Color(255, 255, 255));
        promotionLabel.setText("促销活动");

        roomInformationLabel.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        roomInformationLabel.setForeground(new java.awt.Color(255, 255, 255));
        roomInformationLabel.setText("房间信息");

        updataLabel.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        updataLabel.setForeground(new java.awt.Color(255, 255, 255));
        updataLabel.setText("更新客房信息");

        HotelInformation.setIcon(new javax.swing.ImageIcon("./大作业UI/setting.png")); // NOI18N
        HotelInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HotelInformationMouseClicked(evt);
            }
        });

        settingLabel.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        settingLabel.setForeground(new java.awt.Color(255, 255, 255));
        settingLabel.setText("设置");

        javax.swing.GroupLayout Hotelpart2Layout = new javax.swing.GroupLayout(Hotelpart2);
        Hotelpart2.setLayout(Hotelpart2Layout);
        Hotelpart2Layout.setHorizontalGroup(
            Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hotelpart2Layout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hotelpart2Layout.createSequentialGroup()
                .addGroup(Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Hotelpart2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Hotelpart2Layout.createSequentialGroup()
                                .addComponent(HotelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(userinformation, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Hotelpart2Layout.createSequentialGroup()
                                .addComponent(orderLabel)
                                .addGap(65, 65, 65)
                                .addComponent(UserLabel)))
                        .addGap(71, 71, 71)
                        .addGroup(Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(promotion)
                            .addGroup(Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(HotelOrder1)
                                .addComponent(promotionLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Hotelpart2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updataLabel)
                        .addGap(49, 49, 49)))
                .addGroup(Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Hotelpart2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(settingLabel))
                    .addComponent(roomInformation)
                    .addComponent(roomInformationLabel)
                    .addComponent(HotelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        Hotelpart2Layout.setVerticalGroup(
            Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Hotelpart2Layout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Hotelpart2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(HotelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Hotelpart2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userinformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomInformation, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(promotion, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(promotionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(roomInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HotelOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HotelInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Hotelpart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        mainPanel.add(Hotelpart2);
        Hotelpart2.setBounds(60, 160, 610, 250);
        mainPanel.add(jSeparator1);
        jSeparator1.setBounds(60, 140, 610, 2);
        mainPanel.add(jSeparator4);
        jSeparator4.setBounds(60, 410, 610, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void HotelInformationMouseClicked(java.awt.event.MouseEvent evt) {                                              
        HotelInformationFrame.setVisible(true);
    }                                             

    private void backActionPerformed(java.awt.event.ActionEvent evt) {                                     
      HotelInformationFrame.setVisible(false);
    }                                    

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {     
    	try {
			
			if(RMIClient.getAccountService().hotelLogout(data.getHotelID())){
				HotelInformationFrame.setVisible(false);
				this.setVisible(false);
				new LoginFrame().setVisible(true);
			}
			
		} catch (RemoteException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
        
        
    }                                      

    	private void promotionMouseClicked(java.awt.event.MouseEvent evt) { 
    	
    	try {
    		ArrayList<hotelPromotionPO> list = RMIClient.getPromotionService().getHotelPromotion(data.getHotelID());
    		
    		new hotelPromotionFrame(list,data.getHotelID()).setVisible(true);
    	
    	
    	
    	} catch (RemoteException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
        
    }                                      

    private void userinformationMouseClicked(java.awt.event.MouseEvent evt) {                                             
        new UserDataFrame().setVisible(true);
    }                                            

    private void HotelOrderMouseClicked(java.awt.event.MouseEvent evt) {                                        
        new hotelOrderFrame().setVisible(true);
    }                                       

    private void hotelTelEditActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void hotelNameEditActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void modifyMouseClicked(java.awt.event.MouseEvent evt) {   
    	hotelName.setVisible(false);
    	hotelNameEdit.setVisible(true);
    	HotelTel.setVisible(false);
    	hotelTelEdit.setVisible(true);
    	introduction.setEditable(true);
    	
        modify.setVisible(false);
        save.setVisible(true);
    }                                   

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {    
    	hotelName.setText(hotelNameEdit.getText());
    	hotelName.setVisible(true);
    	hotelNameEdit.setVisible(false);
    	
    	HotelTel.setText(hotelTelEdit.getText());    	
    	HotelTel.setVisible(true);
    	hotelTelEdit.setVisible(false);
    	
    	introduction.setEditable(false);
    	
    	
    	modify.setVisible(true);
    	save.setVisible(false);
       
    }                                 

    /**
     * @param args the command line arguments
     */
   
    private hotelDataVO data;
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel HotelInformation;
    private javax.swing.JInternalFrame HotelInformationFrame;
    private javax.swing.JLabel HotelName;
    private javax.swing.JLabel HotelOrder;
    private javax.swing.JLabel HotelOrder1;
    private javax.swing.JLabel HotelTel;
    private javax.swing.JPanel Hotelpart1;
    private javax.swing.JPanel Hotelpart2;
    private javax.swing.JLabel TelIcon;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JButton back;
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel hotelAccountIcon;
    private javax.swing.JPanel hotelDataBGPanel;
    private javax.swing.JLabel hotelName;
    private javax.swing.JTextField hotelNameEdit;
    private javax.swing.JTextField hotelTelEdit;
    private javax.swing.JTextArea introduction;
    private javax.swing.JLabel introductionIcon;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel modify;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JLabel promotion;
    private javax.swing.JLabel promotionLabel;
    private javax.swing.JLabel roomInformation;
    private javax.swing.JLabel roomInformationLabel;
    private javax.swing.JLabel save;
    private javax.swing.JLabel settingLabel;
    private javax.swing.JLabel updataLabel;
    private javax.swing.JLabel userinformation;
    // End of variables declaration                   
}

