package HotelUI;

import java.rmi.RemoteException;
import java.util.ArrayList;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

import PO.hotelPromotionPO;
import RMICLIENT.RMIClient;
import UI.worngReportFrame;


public class hotelPromotionFrame extends javax.swing.JFrame {

    /**
     * Creates new form hotelPromotionFrame
     */
    public hotelPromotionFrame(ArrayList<hotelPromotionPO> list,String ID) {
        this.list = list;
        this.ID = ID;
    	initComponents();
    	setupPromotion();
    }



	



	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        switchPromotionButtonGroup1 = new javax.swing.ButtonGroup();
        switchPromotionButtonGroup2 = new javax.swing.ButtonGroup();
        switchPromotionButtonGroup3 = new javax.swing.ButtonGroup();
        BGjPanel = new javax.swing.JPanel();
        setPromotionFrame = new javax.swing.JInternalFrame();
        settingBGPanel = new javax.swing.JPanel();
        settingPromotionPanel = new javax.swing.JPanel();
        promotionJTabbedPane = new javax.swing.JTabbedPane();
        promotion1JPanel = new javax.swing.JPanel();
        isFullCut1 = new javax.swing.JRadioButton();
        isDiscount1 = new javax.swing.JRadioButton();
        promoiton1Label = new javax.swing.JLabel();
        NumOfFullCut1 = new javax.swing.JTextField();
        numOfDiscount1 = new javax.swing.JTextField();
        description1 = new javax.swing.JScrollPane();
        DescriptionjTextArea1 = new javax.swing.JTextArea();
        promotionDiscriptionLabel1 = new javax.swing.JLabel();
        fullCutNum1 = new javax.swing.JLabel();
        discountNum1 = new javax.swing.JLabel();
        promotion2JPanel = new javax.swing.JPanel();
        isFullCut2 = new javax.swing.JRadioButton();
        isDiscount2 = new javax.swing.JRadioButton();
        promoiton1Label1 = new javax.swing.JLabel();
        NumOfFullCut2 = new javax.swing.JTextField();
        numOfDiscount2 = new javax.swing.JTextField();
        description2 = new javax.swing.JScrollPane();
        DescriptionjTextArea2 = new javax.swing.JTextArea();
        promotionDiscriptionLabel2 = new javax.swing.JLabel();
        fullCutNum2 = new javax.swing.JLabel();
        discountNum2 = new javax.swing.JLabel();
        promotion3JPanel = new javax.swing.JPanel();
        isFullCut3 = new javax.swing.JRadioButton();
        isDiscount3 = new javax.swing.JRadioButton();
        promoiton1Label2 = new javax.swing.JLabel();
        NumOfFullCut3 = new javax.swing.JTextField();
        numOfDiscount3 = new javax.swing.JTextField();
        description3 = new javax.swing.JScrollPane();
        DescriptionjTextArea3 = new javax.swing.JTextArea();
        promotionDiscriptionLabel3 = new javax.swing.JLabel();
        fullCutNum3 = new javax.swing.JLabel();
        discountNum3 = new javax.swing.JLabel();
        
        addPromotion = new javax.swing.JLabel();
        addDonePromotion = new javax.swing.JLabel();
        
        modifyPromotion = new javax.swing.JLabel();
        delPromotion = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        settingPanel = new javax.swing.JPanel();
        iconLogo = new javax.swing.JLabel();
        hotelName = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        descriptionPromotionPanel = new javax.swing.JPanel();
        promotionIcon2 = new javax.swing.JLabel();
        promotionIcon3 = new javax.swing.JLabel();
        promotionIcon1 = new javax.swing.JLabel();
        promotionDetial2 = new javax.swing.JLabel();
        promotionDetial1 = new javax.swing.JLabel();
        promotionDetial3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(400, 300));
        setResizable(false);

        BGjPanel.setBackground(new java.awt.Color(39, 43, 48));
        BGjPanel.setLayout(null);

        setPromotionFrame.setVisible(false);

        settingBGPanel.setBackground(new java.awt.Color(39, 43, 48));

        settingPromotionPanel.setBackground(new java.awt.Color(0, 76, 68));
        settingPromotionPanel.setLayout(null);

        promotionJTabbedPane.setBackground(new java.awt.Color(0, 76, 68));
        promotionJTabbedPane.setBorder(new javax.swing.border.MatteBorder(null));
        promotionJTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        promotionJTabbedPane.setAutoscrolls(true);
        promotionJTabbedPane.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        promotionJTabbedPane.setInheritsPopupMenu(true);

        promotion1JPanel.setBackground(new java.awt.Color(0, 76, 68));

        isFullCut1.setBackground(new java.awt.Color(0, 76, 68));
        switchPromotionButtonGroup1.add(isFullCut1);
        isFullCut1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        isFullCut1.setForeground(new java.awt.Color(0, 189, 118));
        isFullCut1.setText("满减");
        isFullCut1.setIcon(new javax.swing.ImageIcon("./大作业UI/fail24.png")); // NOI18N
        isFullCut1.setSelectedIcon(new javax.swing.ImageIcon("./大作业UI/Success24.png")); // NOI18N
        isFullCut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isFullCut1ActionPerformed(evt);
            }
        });

        isDiscount1.setBackground(new java.awt.Color(0, 76, 68));
        switchPromotionButtonGroup1.add(isDiscount1);
        isDiscount1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        isDiscount1.setForeground(new java.awt.Color(0, 189, 118));
        isDiscount1.setText("打折");
        isDiscount1.setToolTipText("");
        isDiscount1.setIcon(new javax.swing.ImageIcon("./大作业UI/fail24.png")); // NOI18N
        isDiscount1.setSelectedIcon(new javax.swing.ImageIcon("./大作业UI/Success24.png")); // NOI18N

        promoiton1Label.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        promoiton1Label.setForeground(new java.awt.Color(0, 189, 118));
        promoiton1Label.setText("促销类型");

        NumOfFullCut1.setEditable(false);
        NumOfFullCut1.setBackground(new java.awt.Color(0, 76, 68));
        NumOfFullCut1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        NumOfFullCut1.setForeground(new java.awt.Color(0, 189, 118));
        NumOfFullCut1.setText("0");
        NumOfFullCut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumOfFullCut1ActionPerformed(evt);
            }
        });

        numOfDiscount1.setEditable(false);
        numOfDiscount1.setBackground(new java.awt.Color(0, 76, 68));
        numOfDiscount1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        numOfDiscount1.setForeground(new java.awt.Color(0, 189, 118));
        numOfDiscount1.setText("10");
        numOfDiscount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfDiscount1ActionPerformed(evt);
            }
        });

        DescriptionjTextArea1.setEditable(false);
        DescriptionjTextArea1.setBackground(new java.awt.Color(0, 76, 68));
        DescriptionjTextArea1.setColumns(20);
        DescriptionjTextArea1.setForeground(new java.awt.Color(0, 189, 118));
        DescriptionjTextArea1.setRows(5);
        description1.setViewportView(DescriptionjTextArea1);

        promotionDiscriptionLabel1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        promotionDiscriptionLabel1.setForeground(new java.awt.Color(0, 189, 118));
        promotionDiscriptionLabel1.setText("促销简介");

        fullCutNum1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        fullCutNum1.setForeground(new java.awt.Color(0, 189, 118));
        fullCutNum1.setText("满100减");

        discountNum1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        discountNum1.setForeground(new java.awt.Color(0, 189, 118));
        discountNum1.setText("折扣数");

        javax.swing.GroupLayout promotion1JPanelLayout = new javax.swing.GroupLayout(promotion1JPanel);
        promotion1JPanel.setLayout(promotion1JPanelLayout);
        promotion1JPanelLayout.setHorizontalGroup(
            promotion1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promotion1JPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(promotion1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(promotionDiscriptionLabel1)
                    .addComponent(promoiton1Label))
                .addGap(18, 18, 18)
                .addGroup(promotion1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(promotion1JPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(promotion1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isFullCut1)
                            .addComponent(isDiscount1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(promotion1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullCutNum1)
                            .addComponent(discountNum1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(promotion1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumOfFullCut1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numOfDiscount1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addComponent(description1))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        promotion1JPanelLayout.setVerticalGroup(
            promotion1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promotion1JPanelLayout.createSequentialGroup()
                .addGroup(promotion1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(promotion1JPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(promotion1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumOfFullCut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isFullCut1)
                            .addComponent(fullCutNum1))
                        .addGap(18, 18, 18)
                        .addGroup(promotion1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isDiscount1)
                            .addComponent(numOfDiscount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountNum1)))
                    .addGroup(promotion1JPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(promoiton1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(promotion1JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promotion1JPanelLayout.createSequentialGroup()
                        .addComponent(promotionDiscriptionLabel1)
                        .addGap(29, 29, 29)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        promotionJTabbedPane.addTab("促销一", promotion1JPanel);

        promotion2JPanel.setBackground(new java.awt.Color(0, 76, 68));

        isFullCut2.setBackground(new java.awt.Color(0, 76, 68));
        switchPromotionButtonGroup2.add(isFullCut2);
        isFullCut2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        isFullCut2.setForeground(new java.awt.Color(0, 189, 118));
        isFullCut2.setText("满减");
        isFullCut2.setIcon(new javax.swing.ImageIcon("./大作业UI/fail24.png")); // NOI18N
        isFullCut2.setSelectedIcon(new javax.swing.ImageIcon("./大作业UI/Success24.png")); // NOI18N
        isFullCut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isFullCut2ActionPerformed(evt);
            }
        });

        isDiscount2.setBackground(new java.awt.Color(0, 76, 68));
        switchPromotionButtonGroup2.add(isDiscount2);
        isDiscount2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        isDiscount2.setForeground(new java.awt.Color(0, 189, 118));
        isDiscount2.setText("打折");
        isDiscount2.setToolTipText("");
        isDiscount2.setIcon(new javax.swing.ImageIcon("./大作业UI/fail24.png")); // NOI18N
        isDiscount2.setSelectedIcon(new javax.swing.ImageIcon("./大作业UI/Success24.png")); // NOI18N

        promoiton1Label1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        promoiton1Label1.setForeground(new java.awt.Color(0, 189, 118));
        promoiton1Label1.setText("促销类型");

        NumOfFullCut2.setEditable(false);
        NumOfFullCut2.setBackground(new java.awt.Color(0, 76, 68));
        NumOfFullCut2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        NumOfFullCut2.setForeground(new java.awt.Color(0, 189, 118));
        NumOfFullCut2.setText("0");
        NumOfFullCut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumOfFullCut2ActionPerformed(evt);
            }
        });

        numOfDiscount2.setEditable(false);
        numOfDiscount2.setBackground(new java.awt.Color(0, 76, 68));
        numOfDiscount2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        numOfDiscount2.setForeground(new java.awt.Color(0, 189, 118));
        numOfDiscount2.setText("10");

        DescriptionjTextArea2.setEditable(false);
        DescriptionjTextArea2.setBackground(new java.awt.Color(0, 76, 68));
        DescriptionjTextArea2.setColumns(20);
        DescriptionjTextArea2.setForeground(new java.awt.Color(0, 189, 118));
        DescriptionjTextArea2.setRows(5);
        description2.setViewportView(DescriptionjTextArea2);

        promotionDiscriptionLabel2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        promotionDiscriptionLabel2.setForeground(new java.awt.Color(0, 189, 118));
        promotionDiscriptionLabel2.setText("促销简介");

        fullCutNum2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        fullCutNum2.setForeground(new java.awt.Color(0, 189, 118));
        fullCutNum2.setText("满100减");

        discountNum2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        discountNum2.setForeground(new java.awt.Color(0, 189, 118));
        discountNum2.setText("折扣数");

        javax.swing.GroupLayout promotion2JPanelLayout = new javax.swing.GroupLayout(promotion2JPanel);
        promotion2JPanel.setLayout(promotion2JPanelLayout);
        promotion2JPanelLayout.setHorizontalGroup(
            promotion2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promotion2JPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(promotion2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(promotionDiscriptionLabel2)
                    .addComponent(promoiton1Label1))
                .addGap(18, 18, 18)
                .addGroup(promotion2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(promotion2JPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(promotion2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isFullCut2)
                            .addComponent(isDiscount2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(promotion2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullCutNum2)
                            .addComponent(discountNum2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(promotion2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumOfFullCut2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numOfDiscount2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addComponent(description2))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        promotion2JPanelLayout.setVerticalGroup(
            promotion2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promotion2JPanelLayout.createSequentialGroup()
                .addGroup(promotion2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(promotion2JPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(promotion2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumOfFullCut2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isFullCut2)
                            .addComponent(fullCutNum2))
                        .addGap(18, 18, 18)
                        .addGroup(promotion2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isDiscount2)
                            .addComponent(numOfDiscount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountNum2)))
                    .addGroup(promotion2JPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(promoiton1Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(promotion2JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promotion2JPanelLayout.createSequentialGroup()
                        .addComponent(promotionDiscriptionLabel2)
                        .addGap(29, 29, 29)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        promotionJTabbedPane.addTab("促销二", promotion2JPanel);

        promotion3JPanel.setBackground(new java.awt.Color(0, 76, 68));

        isFullCut3.setBackground(new java.awt.Color(0, 76, 68));
        switchPromotionButtonGroup3.add(isFullCut3);
        isFullCut3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        isFullCut3.setForeground(new java.awt.Color(0, 189, 118));
        isFullCut3.setText("满减");
        isFullCut3.setIcon(new javax.swing.ImageIcon("./大作业UI/fail24.png")); // NOI18N
        isFullCut3.setSelectedIcon(new javax.swing.ImageIcon("./大作业UI/Success24.png")); // NOI18N
        isFullCut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isFullCut3ActionPerformed(evt);
            }
        });

        isDiscount3.setBackground(new java.awt.Color(0, 76, 68));
        switchPromotionButtonGroup3.add(isDiscount3);
        isDiscount3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        isDiscount3.setForeground(new java.awt.Color(0, 189, 118));
        isDiscount3.setText("打折");
        isDiscount3.setToolTipText("");
        isDiscount3.setIcon(new javax.swing.ImageIcon("./大作业UI/fail24.png")); // NOI18N
        isDiscount3.setSelectedIcon(new javax.swing.ImageIcon("./大作业UI/Success24.png")); // NOI18N

        promoiton1Label2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        promoiton1Label2.setForeground(new java.awt.Color(0, 189, 118));
        promoiton1Label2.setText("促销类型");

        NumOfFullCut3.setEditable(false);
        NumOfFullCut3.setBackground(new java.awt.Color(0, 76, 68));
        NumOfFullCut3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        NumOfFullCut3.setForeground(new java.awt.Color(0, 189, 118));
        NumOfFullCut3.setText("0");
        NumOfFullCut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumOfFullCut3ActionPerformed(evt);
            }
        });

        numOfDiscount3.setEditable(false);
        numOfDiscount3.setBackground(new java.awt.Color(0, 76, 68));
        numOfDiscount3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        numOfDiscount3.setForeground(new java.awt.Color(0, 189, 118));
        numOfDiscount3.setText("10");

        DescriptionjTextArea3.setEditable(false);
        DescriptionjTextArea3.setBackground(new java.awt.Color(0, 76, 68));
        DescriptionjTextArea3.setColumns(20);
        DescriptionjTextArea3.setForeground(new java.awt.Color(0, 189, 118));
        DescriptionjTextArea3.setRows(5);
        description3.setViewportView(DescriptionjTextArea3);

        promotionDiscriptionLabel3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        promotionDiscriptionLabel3.setForeground(new java.awt.Color(0, 189, 118));
        promotionDiscriptionLabel3.setText("促销简介");

        fullCutNum3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        fullCutNum3.setForeground(new java.awt.Color(0, 189, 118));
        fullCutNum3.setText("满100减");

        discountNum3.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        discountNum3.setForeground(new java.awt.Color(0, 189, 118));
        discountNum3.setText("折扣数");

        javax.swing.GroupLayout promotion3JPanelLayout = new javax.swing.GroupLayout(promotion3JPanel);
        promotion3JPanel.setLayout(promotion3JPanelLayout);
        promotion3JPanelLayout.setHorizontalGroup(
            promotion3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promotion3JPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(promotion3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(promotionDiscriptionLabel3)
                    .addComponent(promoiton1Label2))
                .addGap(18, 18, 18)
                .addGroup(promotion3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(promotion3JPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(promotion3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isFullCut3)
                            .addComponent(isDiscount3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(promotion3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullCutNum3)
                            .addComponent(discountNum3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(promotion3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumOfFullCut3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numOfDiscount3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addComponent(description3))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        promotion3JPanelLayout.setVerticalGroup(
            promotion3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promotion3JPanelLayout.createSequentialGroup()
                .addGroup(promotion3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(promotion3JPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(promotion3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumOfFullCut3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isFullCut3)
                            .addComponent(fullCutNum3))
                        .addGap(18, 18, 18)
                        .addGroup(promotion3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isDiscount3)
                            .addComponent(numOfDiscount3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountNum3)))
                    .addGroup(promotion3JPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(promoiton1Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(promotion3JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promotion3JPanelLayout.createSequentialGroup()
                        .addComponent(promotionDiscriptionLabel3)
                        .addGap(29, 29, 29)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        promotionJTabbedPane.addTab("促销三", promotion3JPanel);

        settingPromotionPanel.add(promotionJTabbedPane);
        promotionJTabbedPane.setBounds(14, 13, 524, 292);

        addPromotion.setIcon(new javax.swing.ImageIcon("./大作业UI/add48.png")); // NOI18N
        addPromotion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPromotionMouseClicked(evt);
            }
        });
        settingPromotionPanel.add(addPromotion);
        addPromotion.setBounds(570, 20, 50, 50);

        modifyPromotion.setIcon(new javax.swing.ImageIcon("./大作业UI/modify48.png")); // NOI18N
        modifyPromotion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyPromotionMouseClicked(evt);
            }
        });
        settingPromotionPanel.add(modifyPromotion);
        modifyPromotion.setBounds(570, 100, 50, 48);

        delPromotion.setIcon(new javax.swing.ImageIcon("./大作业UI/Scissors48.png")); // NOI18N
        delPromotion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delPromotionMouseClicked(evt);
            }
        });
        settingPromotionPanel.add(delPromotion);
        delPromotion.setBounds(570, 180, 50, 48);

        back.setIcon(new javax.swing.ImageIcon("./大作业UI/backwards.png")); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        settingPromotionPanel.add(back);
        back.setBounds(570, 260, 50, 48);

        save.setIcon(new javax.swing.ImageIcon("./大作业UI/save.png")); // NOI18N
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        settingPromotionPanel.add(save);
        save.setBounds(570, 100, 50, 50);
        
        addDonePromotion.setIcon(new javax.swing.ImageIcon("./大作业UI/save.png")); // NOI18N
        addDonePromotion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDonePromotionMouseClicked(evt);
            }
        });
        settingPromotionPanel.add(addDonePromotion);
        addDonePromotion.setBounds(570, 20, 50, 50);

        javax.swing.GroupLayout settingBGPanelLayout = new javax.swing.GroupLayout(settingBGPanel);
        settingBGPanel.setLayout(settingBGPanelLayout);
        settingBGPanelLayout.setHorizontalGroup(
            settingBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingBGPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingPromotionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        settingBGPanelLayout.setVerticalGroup(
            settingBGPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingBGPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingPromotionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout setPromotionFrameLayout = new javax.swing.GroupLayout(setPromotionFrame.getContentPane());
        setPromotionFrame.getContentPane().setLayout(setPromotionFrameLayout);
        setPromotionFrameLayout.setHorizontalGroup(
            setPromotionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingBGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        setPromotionFrameLayout.setVerticalGroup(
            setPromotionFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingBGPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BGjPanel.add(setPromotionFrame);
        setPromotionFrame.setBounds(30, 30, 680, 380);

        settingPanel.setBackground(new java.awt.Color(0, 76, 68));

        iconLogo.setIcon(new javax.swing.ImageIcon("./大作业UI/Bank.png")); // NOI18N

        hotelName.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        hotelName.setForeground(new java.awt.Color(0, 211, 81));
        hotelName.setText("酒店的促销策略");

        setting.setIcon(new javax.swing.ImageIcon("./大作业UI/Settings2.png")); // NOI18N
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(iconLogo)
                .addGap(26, 26, 26)
                .addComponent(hotelName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(setting)
                .addGap(46, 46, 46))
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(setting)
                    .addComponent(hotelName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconLogo))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        BGjPanel.add(settingPanel);
        settingPanel.setBounds(38, 38, 670, 93);

        descriptionPromotionPanel.setBackground(new java.awt.Color(0, 76, 68));

        promotionIcon2.setIcon(new javax.swing.ImageIcon("./大作业UI/promotion.png")); // NOI18N

        promotionIcon3.setIcon(new javax.swing.ImageIcon("./大作业UI/promotion.png")); // NOI18N

        promotionIcon1.setIcon(new javax.swing.ImageIcon("./大作业UI/promotion.png")); // NOI18N

        promotionDetial2.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        promotionDetial2.setForeground(new java.awt.Color(0, 211, 81));
        promotionDetial2.setText("策略二");

        promotionDetial1.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        promotionDetial1.setForeground(new java.awt.Color(0, 211, 81));
        promotionDetial1.setText("策略一");

        promotionDetial3.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        promotionDetial3.setForeground(new java.awt.Color(0, 211, 81));
        promotionDetial3.setText("策略三");

        javax.swing.GroupLayout descriptionPromotionPanelLayout = new javax.swing.GroupLayout(descriptionPromotionPanel);
        descriptionPromotionPanel.setLayout(descriptionPromotionPanelLayout);
        descriptionPromotionPanelLayout.setHorizontalGroup(
            descriptionPromotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPromotionPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(descriptionPromotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(promotionIcon1)
                    .addComponent(promotionIcon2)
                    .addComponent(promotionIcon3))
                .addGap(26, 26, 26)
                .addGroup(descriptionPromotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(promotionDetial2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(promotionDetial3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(promotionDetial1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        descriptionPromotionPanelLayout.setVerticalGroup(
            descriptionPromotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPromotionPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(descriptionPromotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(promotionIcon1)
                    .addComponent(promotionDetial1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(descriptionPromotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(promotionDetial2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(promotionIcon2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(descriptionPromotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(promotionIcon3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(promotionDetial3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        BGjPanel.add(descriptionPromotionPanel);
        descriptionPromotionPanel.setBounds(38, 149, 670, 272);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        
        
        

        pack();
    }// </editor-fold>                        

    private void NumOfFullCut1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void isFullCut1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void isFullCut2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void NumOfFullCut2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void isFullCut3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void NumOfFullCut3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    
    
    //新增promotion
    private void addPromotionMouseClicked(java.awt.event.MouseEvent evt) {      
        for(int i = 0; i < 3; i++){
        	if(!existPromotion[i]){
        		promotionJTabbedPane.setSelectedIndex(i);
        		if(i==0){
        			setInputVisibleTrue(isFullCut1,isDiscount1,NumOfFullCut1,
        					numOfDiscount1,DescriptionjTextArea1);
              		 addPromotion.setVisible(false);
            		 addDonePromotion.setVisible(true);
        		}else if(i==1){
        			setInputVisibleTrue(isFullCut2,isDiscount2,NumOfFullCut2,
        					numOfDiscount2,DescriptionjTextArea2);
             		 addPromotion.setVisible(false);
             		 addDonePromotion.setVisible(true);
        		}else if(i==2){
        			setInputVisibleTrue(isFullCut3,isDiscount3,NumOfFullCut3,
        					numOfDiscount3,DescriptionjTextArea3);
             		 addPromotion.setVisible(false);
             		 addDonePromotion.setVisible(true);
        		}
        		break;
        	}else{
    			
    			
    		}
        }
        
        new worngReportFrame("已经满了三个促销策略，请直接修改或者删除促销策略").setVisible(true);
    }                   
    
    //准备新增之后的，保存传向服务器的过程
    private void addDonePromotionMouseClicked(java.awt.event.MouseEvent evt) {      
    	hotelPromotionPO promotion = new hotelPromotionPO();
    	 for(int i = 0; i < 3; i++){
         	if(!existPromotion[i]){
         		if(i==0){
         			promotion = setupPromotionPO("1",isFullCut1.isSelected(),Integer.parseInt(NumOfFullCut1.getText()),
            				isDiscount1.isSelected(),Double.parseDouble(numOfDiscount1.getText()),
            				DescriptionjTextArea1.getText());
         			setInputVisibleFalse(isFullCut1,isDiscount1,NumOfFullCut1,
        					numOfDiscount1,DescriptionjTextArea1);
         			promotionDetial1.setText(DescriptionjTextArea1.getText());//主界面的label简短描述策略
        		}else if(i==1){
        			promotion = setupPromotionPO("2",isFullCut2.isSelected(),Integer.parseInt(NumOfFullCut2.getText()),
            				isDiscount2.isSelected(),Double.parseDouble(numOfDiscount2.getText()),
            				DescriptionjTextArea2.getText());
        			setInputVisibleFalse(isFullCut2,isDiscount2,NumOfFullCut2,
        					numOfDiscount2,DescriptionjTextArea2);
        			promotionDetial2.setText(DescriptionjTextArea2.getText());//主界面的label简短描述策略
        		}else if(i==2){
        			
        			promotion = setupPromotionPO("3",isFullCut3.isSelected(),Integer.parseInt(NumOfFullCut3.getText()),
            				isDiscount3.isSelected(),Double.parseDouble(numOfDiscount3.getText()),
            				DescriptionjTextArea3.getText());
        			setInputVisibleFalse(isFullCut3,isDiscount3,NumOfFullCut3,
        					numOfDiscount3,DescriptionjTextArea3);
        			promotionDetial3.setText(DescriptionjTextArea3.getText());
        		}
         		
         		try {
					RMIClient.getPromotionService().AddNewPromotion(ID, promotion);
					existPromotion[i] = true;
				} catch (RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
         		
         		 addPromotion.setVisible(true);
         		 addDonePromotion.setVisible(false);
         		break;
         	}
         }
    }      
    

    private void modifyPromotionMouseClicked(java.awt.event.MouseEvent evt) {  
        if(promotionJTabbedPane.getSelectedIndex()==0){ //修改策略1
        	if(list.get(0)!=null){
        		 modifyPromotion.setVisible(false);
        		 save.setVisible(true);
        		 setInputVisibleTrue(isFullCut1,isDiscount1,NumOfFullCut1,
     					numOfDiscount1,DescriptionjTextArea1);
        	}else{
        		new worngReportFrame("没有策略一\n请先创建").setVisible(true);
        	}
        	
        }else if(promotionJTabbedPane.getSelectedIndex()==1){//修改策略2
        	if(list.get(1)!=null){
        		modifyPromotion.setVisible(false);
        		save.setVisible(true);
        		setInputVisibleTrue(isFullCut2,isDiscount2,NumOfFullCut2,
     					numOfDiscount2,DescriptionjTextArea2);
        	}else{
        		
        		new worngReportFrame("没有策略二\n请先创建").setVisible(true);
        		
        	}	
        }else if(promotionJTabbedPane.getSelectedIndex()==2){//修改策略3
        	if(list.get(2)!=null){
       		 	modifyPromotion.setVisible(false);
       		 	save.setVisible(true);
       		 setInputVisibleTrue(isFullCut3,isDiscount3,NumOfFullCut3,
  					numOfDiscount3,DescriptionjTextArea3);
        	}else{
        		new worngReportFrame("没有策略三\n请先创建").setVisible(true);
        	}
        }
        
        
    }                                            

    private void delPromotionMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void backMouseClicked(java.awt.event.MouseEvent evt) {                                  
        setPromotionFrame.setVisible(false);
    }                                 

    private void numOfDiscount1ActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void settingMouseClicked(java.awt.event.MouseEvent evt) {                                     
       setPromotionFrame.setVisible(true);
    }                                    

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {        //修改之后的保存的监听
    	hotelPromotionPO promotion = new hotelPromotionPO();
    	if(promotionJTabbedPane.getSelectedIndex()==0){//第一个政策时
    		promotion = setupPromotionPO("1",isFullCut1.isSelected(),Integer.parseInt(NumOfFullCut1.getText()),
    				isDiscount1.isSelected(),Double.parseDouble(numOfDiscount1.getText()),
    				DescriptionjTextArea1.getText());
    		try {
				RMIClient.getPromotionService().modifyHotelPromotion(ID, promotion);
				promotionDetial1.setText(DescriptionjTextArea1.getText());//主界面的label简短描述策略
			} catch (RemoteException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    		setInputVisibleFalse(isFullCut1,isDiscount1,NumOfFullCut1,
					numOfDiscount1,DescriptionjTextArea1);
    		
    	}else if(promotionJTabbedPane.getSelectedIndex()==1){//第二个政策时
    		promotion = setupPromotionPO("2",isFullCut2.isSelected(),Integer.parseInt(NumOfFullCut2.getText()),
    				isDiscount2.isSelected(),Double.parseDouble(numOfDiscount2.getText()),
    				DescriptionjTextArea2.getText());
    		try {
				RMIClient.getPromotionService().modifyHotelPromotion(ID, promotion);
				promotionDetial2.setText(DescriptionjTextArea2.getText());//主界面的label简短描述策略
			} catch (RemoteException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    		setInputVisibleFalse(isFullCut2,isDiscount2,NumOfFullCut2,
					numOfDiscount2,DescriptionjTextArea2);
    		
    	}else if(promotionJTabbedPane.getSelectedIndex()==2){
    		promotion = setupPromotionPO("3",isFullCut3.isSelected(),Integer.parseInt(NumOfFullCut3.getText()),
    				isDiscount3.isSelected(),Double.parseDouble(numOfDiscount3.getText()),
    				DescriptionjTextArea3.getText());
     		try {
    			
				RMIClient.getPromotionService().modifyHotelPromotion(ID, promotion);
				promotionDetial3.setText(DescriptionjTextArea3.getText());//主界面的label简短描述策略
			} catch (RemoteException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
     		setInputVisibleFalse(isFullCut3,isDiscount3,NumOfFullCut3,
					numOfDiscount3,DescriptionjTextArea3);
    	}
    	save.setVisible(false);
		modifyPromotion.setVisible(true);	
    }                                 

    
    //设置修改或者新增promotion输入数据的可写性
    private void setInputVisibleTrue(JRadioButton isFullCut,JRadioButton isDiscount,JTextField NumOfFullCut,
    		JTextField numOfDiscount, JTextArea DescriptionjTextArea){
    	 isFullCut.setEnabled(true);
 		 isDiscount.setEnabled(true);
 		 NumOfFullCut.setEditable(true);
 		 numOfDiscount.setEditable(true);
 		 DescriptionjTextArea.setEditable(true);
 		 
    }
    //设置修改或者新增promotion输入数据的不可写性
    private void setInputVisibleFalse(JRadioButton isFullCut,JRadioButton isDiscount,JTextField NumOfFullCut,
    		JTextField numOfDiscount, JTextArea DescriptionjTextArea){
    	 isFullCut.setEnabled(false);
 		 isDiscount.setEnabled(false);
 		 NumOfFullCut.setEditable(false);
 		 numOfDiscount.setEditable(false);
 		 DescriptionjTextArea.setEditable(false);
 		 
    }
    
    
    
    //修改促销策略的通用方法
    private hotelPromotionPO setupPromotionPO(String serial,boolean isFullCut,int NumOfFullCut,
    	boolean isDiscount, double	numOfDiscount,String DescriptionjTextArea){
    	hotelPromotionPO promotion = new hotelPromotionPO();
    	promotion.setSerial(serial);
		promotion.setIsFullCut(isFullCut);
		promotion.setMoneyCut(NumOfFullCut);
		promotion.setIsDiscount(isDiscount);
		promotion.setDiscount(numOfDiscount);
		promotion.setPrmotionDescription(DescriptionjTextArea);
    	return promotion;
    }
    
    private void setupPromotion(){
    	if(list.size()>=1){
    		if(list.get(0).getIsFullCut()){
    			isFullCut1.setSelected(true);
    			NumOfFullCut1.setText(Integer.toString(list.get(0).getMoneyCut()));
    		}else{
    			
    			isDiscount1.setSelected(true);
    			numOfDiscount1.setText(Double.toString(list.get(0).getdiscount()));
    		
    		}
    		DescriptionjTextArea1.setText(list.get(0).getPromotionDescription());
    		promotionDetial1.setText(list.get(0).getPromotionDescription());
    		existPromotion[0] = true;
    	}
    	if(list.size()>=2){
    		if(list.get(1).getIsFullCut()){
    			
    			isFullCut2.setSelected(true);
    			NumOfFullCut2.setText(Integer.toString(list.get(1).getMoneyCut()));
    		}else{
    			isDiscount2.setSelected(true);
    			numOfDiscount2.setText(Double.toString(list.get(1).getdiscount()));
    		}
    		DescriptionjTextArea2.setText(list.get(1).getPromotionDescription());
    		
    		promotionDetial2.setText(list.get(1).getPromotionDescription());
    		existPromotion[1] = true;
    		
    	}
    	if(list.size()>=3){
    		if(list.get(2).getIsFullCut()){
    			isFullCut3.setSelected(true);
    			NumOfFullCut3.setText(Integer.toString(list.get(2).getMoneyCut()));
    		}else{
    			isDiscount3.setSelected(true);
    			numOfDiscount3.setText(Double.toString(list.get(2).getdiscount()));
    		}
    		DescriptionjTextArea3.setText(list.get(2).getPromotionDescription());
    		promotionDetial3.setText(list.get(2).getPromotionDescription());
    		existPromotion[2] = true;
    		
    	}
    	if(list.size()==0){
    		
    	}
    	
    	isFullCut1.setEnabled(false);
    	isFullCut2.setEnabled(false);
    	isFullCut3.setEnabled(false);
    	isDiscount1.setEnabled(false);
    	isDiscount2.setEnabled(false);
    	isDiscount3.setEnabled(false);
    }
    
    
    private boolean []existPromotion = {false,false,false};
    private ArrayList<hotelPromotionPO> list;
    private String ID;

    // Variables declaration - do not modify                     
    private javax.swing.JPanel BGjPanel;
    private javax.swing.JTextArea DescriptionjTextArea1;
    private javax.swing.JTextArea DescriptionjTextArea2;
    private javax.swing.JTextArea DescriptionjTextArea3;
    private javax.swing.JTextField NumOfFullCut1;
    private javax.swing.JTextField NumOfFullCut2;
    private javax.swing.JTextField NumOfFullCut3;
    
    private javax.swing.JLabel addPromotion;
    private javax.swing.JLabel addDonePromotion;
    
    private javax.swing.JLabel back;
    private javax.swing.JLabel delPromotion;
    private javax.swing.JScrollPane description1;
    private javax.swing.JScrollPane description2;
    private javax.swing.JScrollPane description3;
    private javax.swing.JPanel descriptionPromotionPanel;
    private javax.swing.JLabel discountNum1;
    private javax.swing.JLabel discountNum2;
    private javax.swing.JLabel discountNum3;
    private javax.swing.JLabel fullCutNum1;
    private javax.swing.JLabel fullCutNum2;
    private javax.swing.JLabel fullCutNum3;
    private javax.swing.JLabel hotelName;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JRadioButton isDiscount1;
    private javax.swing.JRadioButton isDiscount2;
    private javax.swing.JRadioButton isDiscount3;
    private javax.swing.JRadioButton isFullCut1;
    private javax.swing.JRadioButton isFullCut2;
    private javax.swing.JRadioButton isFullCut3;
    private javax.swing.JLabel modifyPromotion;
    private javax.swing.JTextField numOfDiscount1;
    private javax.swing.JTextField numOfDiscount2;
    private javax.swing.JTextField numOfDiscount3;
    private javax.swing.JLabel promoiton1Label;
    private javax.swing.JLabel promoiton1Label1;
    private javax.swing.JLabel promoiton1Label2;
    private javax.swing.JPanel promotion1JPanel;
    private javax.swing.JPanel promotion2JPanel;
    private javax.swing.JPanel promotion3JPanel;
    private javax.swing.JLabel promotionDetial1;
    private javax.swing.JLabel promotionDetial2;
    private javax.swing.JLabel promotionDetial3;
    private javax.swing.JLabel promotionDiscriptionLabel1;
    private javax.swing.JLabel promotionDiscriptionLabel2;
    private javax.swing.JLabel promotionDiscriptionLabel3;
    private javax.swing.JLabel promotionIcon1;
    private javax.swing.JLabel promotionIcon2;
    private javax.swing.JLabel promotionIcon3;
    private javax.swing.JTabbedPane promotionJTabbedPane;
    private javax.swing.JLabel save;
    private javax.swing.JInternalFrame setPromotionFrame;
    private javax.swing.JLabel setting;
    private javax.swing.JPanel settingBGPanel;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JPanel settingPromotionPanel;
    private javax.swing.ButtonGroup switchPromotionButtonGroup1;
    private javax.swing.ButtonGroup switchPromotionButtonGroup2;
    private javax.swing.ButtonGroup switchPromotionButtonGroup3;
    // End of variables declaration                   
}


