package HotelUI;

public class UserDataFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserDataFrame
     */
    public UserDataFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        background = new javax.swing.JPanel();
        userNameFrame = new javax.swing.JInternalFrame();
        next = new javax.swing.JButton();
        userListScrollPanel = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        userListPicture = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        showDataPanel = new javax.swing.JPanel();
        showTopSeparator = new javax.swing.JSeparator();
        showLowSeparator = new javax.swing.JSeparator();
        userNamePicture = new javax.swing.JLabel();
        showUserName = new javax.swing.JLabel();
        userCommunicatePicture = new javax.swing.JLabel();
        showCommunicate = new javax.swing.JLabel();
        roomTypePicture = new javax.swing.JLabel();
        showRoomType = new javax.swing.JLabel();
        orderStatuePicture = new javax.swing.JLabel();
        showOrderStatue = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchTopSeparator = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        searchButton = new javax.swing.JLabel();
        SearchLabel1 = new javax.swing.JLabel();
        allUserName = new javax.swing.JLabel();
        searchLowSeparator = new javax.swing.JSeparator();

        setBounds(new java.awt.Rectangle(400, 300, 0, 0));
        setPreferredSize(new java.awt.Dimension(765, 470));
        setSize(new java.awt.Dimension(800, 500));

        background.setBackground(new java.awt.Color(39, 43, 48));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(747, 424));
        background.setLayout(null);

        userNameFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        userNameFrame.setVisible(false);

        next.setText("确定");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "UserName"
            }
        ));
        userListScrollPanel.setViewportView(jTable1);

        userListPicture.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        userListPicture.setText("用户列表");

        back.setText("取消");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userNameFrameLayout = new javax.swing.GroupLayout(userNameFrame.getContentPane());
        userNameFrame.getContentPane().setLayout(userNameFrameLayout);
        userNameFrameLayout.setHorizontalGroup(
            userNameFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userListScrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(userNameFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userNameFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userListPicture, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        userNameFrameLayout.setVerticalGroup(
            userNameFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userNameFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userListPicture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userListScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(next)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(userNameFrame);
        userNameFrame.setBounds(560, 10, 160, 410);

        showDataPanel.setBackground(new java.awt.Color(0, 76, 68));

        userNamePicture.setIcon(new javax.swing.ImageIcon("./大作业UI/person.png")); // NOI18N

        showUserName.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        showUserName.setText("用户名");

        userCommunicatePicture.setIcon(new javax.swing.ImageIcon("./大作业UI/communicate.png")); // NOI18N

        showCommunicate.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        showCommunicate.setText("通讯方式");

        roomTypePicture.setIcon(new javax.swing.ImageIcon("./大作业UI/Home.png")); // NOI18N

        showRoomType.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        showRoomType.setText("房间类型");

        orderStatuePicture.setIcon(new javax.swing.ImageIcon("./大作业UI/statue.png")); // NOI18N

        showOrderStatue.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        showOrderStatue.setText("订单状态");

        javax.swing.GroupLayout showDataPanelLayout = new javax.swing.GroupLayout(showDataPanel);
        showDataPanel.setLayout(showDataPanelLayout);
        showDataPanelLayout.setHorizontalGroup(
            showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showTopSeparator)
            .addComponent(showLowSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(showDataPanelLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userCommunicatePicture)
                    .addComponent(userNamePicture)
                    .addComponent(roomTypePicture)
                    .addComponent(orderStatuePicture))
                .addGap(27, 27, 27)
                .addGroup(showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showOrderStatue, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showCommunicate, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        showDataPanelLayout.setVerticalGroup(
            showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showDataPanelLayout.createSequentialGroup()
                .addComponent(showTopSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNamePicture)
                    .addComponent(showUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userCommunicatePicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(showDataPanelLayout.createSequentialGroup()
                        .addComponent(showCommunicate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roomTypePicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showRoomType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(showDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showOrderStatue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderStatuePicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(showLowSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(showDataPanel);
        showDataPanel.setBounds(14, 131, 718, 278);

        searchPanel.setBackground(new java.awt.Color(0, 76, 68));

        jTextField1.setBackground(new java.awt.Color(53, 74, 75));
        jTextField1.setFont(new java.awt.Font("微软雅黑", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 153, 153));

        searchButton.setIcon(new javax.swing.ImageIcon("./大作业UI/search.png")); // NOI18N

        SearchLabel1.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        SearchLabel1.setForeground(new java.awt.Color(255, 255, 255));
        SearchLabel1.setText("搜索一下");

        allUserName.setIcon(new javax.swing.ImageIcon("./大作业UI/menu.png")); // NOI18N
        allUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allUserNameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchTopSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addGap(18, 18, 18)
                .addComponent(allUserName)
                .addGap(64, 64, 64))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(searchTopSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1)
                        .addComponent(SearchLabel1))
                    .addComponent(searchButton)
                    .addComponent(allUserName))
                .addContainerGap())
        );

        background.add(searchPanel);
        searchPanel.setBounds(14, 31, 718, 81);
        background.add(searchLowSeparator);
        searchLowSeparator.setBounds(14, 114, 718, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void allUserNameMouseClicked(java.awt.event.MouseEvent evt) {                                         
       userNameFrame.setVisible(true);
    }                                        

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {                                     
        userNameFrame.setVisible(false);
    }                                    

    private void backActionPerformed(java.awt.event.ActionEvent evt) {                                     
        userNameFrame.setVisible(false);
    }                                    

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify                     
    private javax.swing.JLabel SearchLabel1;
    private javax.swing.JLabel allUserName;
    private javax.swing.JButton back;
    private javax.swing.JPanel background;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton next;
    private javax.swing.JLabel orderStatuePicture;
    private javax.swing.JLabel roomTypePicture;
    private javax.swing.JLabel searchButton;
    private javax.swing.JSeparator searchLowSeparator;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JSeparator searchTopSeparator;
    private javax.swing.JLabel showCommunicate;
    private javax.swing.JPanel showDataPanel;
    private javax.swing.JSeparator showLowSeparator;
    private javax.swing.JLabel showOrderStatue;
    private javax.swing.JLabel showRoomType;
    private javax.swing.JSeparator showTopSeparator;
    private javax.swing.JLabel showUserName;
    private javax.swing.JLabel userCommunicatePicture;
    private javax.swing.JLabel userListPicture;
    private javax.swing.JScrollPane userListScrollPanel;
    private javax.swing.JInternalFrame userNameFrame;
    private javax.swing.JLabel userNamePicture;
    // End of variables declaration                   
}

