package UserUI;

import VO.userDataVO;

/**
 *
 * @author 江回晖
 */
public class CommentFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConmmentFrame
     */
    public CommentFrame(userDataVO data) {
    	this.data = data;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentjTextArea = new javax.swing.JTextArea();
        returnjButton = new javax.swing.JButton();
        commitjButton = new javax.swing.JButton();
        equipgoodjRadioButton = new javax.swing.JRadioButton();
        equipbadjRadioButton = new javax.swing.JRadioButton();
        equipcommonjRadioButton = new javax.swing.JRadioButton();
        roombadjRadioButton = new javax.swing.JRadioButton();
        hotelbadjRadioButton = new javax.swing.JRadioButton();
        roomcommonjRadioButton = new javax.swing.JRadioButton();
        hotelcommonjRadioButton = new javax.swing.JRadioButton();
        roomgoodjRadioButton = new javax.swing.JRadioButton();
        hotelgoodjRadioButton = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 180));
        
        buttonGroup1.add(roombadjRadioButton);
        buttonGroup1.add(roomcommonjRadioButton);
        buttonGroup1.add(roomgoodjRadioButton);
        
        buttonGroup2.add(hotelbadjRadioButton);
        buttonGroup2.add(hotelcommonjRadioButton);
        buttonGroup2.add(hotelgoodjRadioButton);
        
        buttonGroup3.add(equipbadjRadioButton);
        buttonGroup3.add(equipcommonjRadioButton);
        buttonGroup3.add(equipgoodjRadioButton);

        jPanel1.setBackground(new java.awt.Color(0, 76, 68));
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 70, 365, 2);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 140, 365, 2);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("设备设施");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 160, 96, 35);

        jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("房间卫生");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 20, 96, 35);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(0, 210, 370, 2);

        jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("酒店环境");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 90, 96, 35);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(0, 320, 370, 2);

        commentjTextArea.setColumns(20);
        commentjTextArea.setRows(5);
        jScrollPane1.setViewportView(commentjTextArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 220, 370, 90);

        returnjButton.setBackground(new java.awt.Color(0, 76, 68));
        returnjButton.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        returnjButton.setForeground(new java.awt.Color(153, 255, 153));
        returnjButton.setText("返回");
        jPanel1.add(returnjButton);
        returnjButton.setBounds(200, 350, 110, 50);
        returnjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	returnjButtonActionPerformed(evt);
            }
        });

        commitjButton.setBackground(new java.awt.Color(0, 76, 68));
        commitjButton.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        commitjButton.setForeground(new java.awt.Color(153, 255, 153));
        commitjButton.setText("提交");
        jPanel1.add(commitjButton);
        commitjButton.setBounds(40, 350, 110, 50);
        commitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	commitjButtonActionPerformed(evt);
            }
        });

        equipgoodjRadioButton.setBackground(new java.awt.Color(0, 76, 68));
        equipgoodjRadioButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        equipgoodjRadioButton.setForeground(new java.awt.Color(153, 255, 153));
        equipgoodjRadioButton.setText("很好");
        equipgoodjRadioButton.setToolTipText("");
        jPanel1.add(equipgoodjRadioButton);
        equipgoodjRadioButton.setBounds(290, 170, 70, 20);

        equipbadjRadioButton.setBackground(new java.awt.Color(0, 76, 68));
        equipbadjRadioButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        equipbadjRadioButton.setForeground(new java.awt.Color(153, 255, 153));
        equipbadjRadioButton.setText("差");
        jPanel1.add(equipbadjRadioButton);
        equipbadjRadioButton.setBounds(110, 170, 70, 20);

        equipcommonjRadioButton.setBackground(new java.awt.Color(0, 76, 68));
        equipcommonjRadioButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        equipcommonjRadioButton.setForeground(new java.awt.Color(153, 255, 153));
        equipcommonjRadioButton.setText("一般");
        equipcommonjRadioButton.setToolTipText("");
        jPanel1.add(equipcommonjRadioButton);
        equipcommonjRadioButton.setBounds(190, 170, 70, 20);

        roombadjRadioButton.setBackground(new java.awt.Color(0, 76, 68));
        roombadjRadioButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        roombadjRadioButton.setForeground(new java.awt.Color(153, 255, 153));
        roombadjRadioButton.setText("差");
        jPanel1.add(roombadjRadioButton);
        roombadjRadioButton.setBounds(110, 30, 70, 20);

        hotelbadjRadioButton.setBackground(new java.awt.Color(0, 76, 68));
        hotelbadjRadioButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        hotelbadjRadioButton.setForeground(new java.awt.Color(153, 255, 153));
        hotelbadjRadioButton.setText("差");
        jPanel1.add(hotelbadjRadioButton);
        hotelbadjRadioButton.setBounds(110, 100, 70, 20);

        roomcommonjRadioButton.setBackground(new java.awt.Color(0, 76, 68));
        roomcommonjRadioButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        roomcommonjRadioButton.setForeground(new java.awt.Color(153, 255, 153));
        roomcommonjRadioButton.setText("一般");
        roomcommonjRadioButton.setToolTipText("");
        jPanel1.add(roomcommonjRadioButton);
        roomcommonjRadioButton.setBounds(190, 30, 70, 20);

        hotelcommonjRadioButton.setBackground(new java.awt.Color(0, 76, 68));
        hotelcommonjRadioButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        hotelcommonjRadioButton.setForeground(new java.awt.Color(153, 255, 153));
        hotelcommonjRadioButton.setText("一般");
        hotelcommonjRadioButton.setToolTipText("");
        jPanel1.add(hotelcommonjRadioButton);
        hotelcommonjRadioButton.setBounds(190, 100, 70, 20);

        roomgoodjRadioButton.setBackground(new java.awt.Color(0, 76, 68));
        roomgoodjRadioButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        roomgoodjRadioButton.setForeground(new java.awt.Color(153, 255, 153));
        roomgoodjRadioButton.setText("很好");
        roomgoodjRadioButton.setToolTipText("");
        jPanel1.add(roomgoodjRadioButton);
        roomgoodjRadioButton.setBounds(290, 30, 70, 20);

        hotelgoodjRadioButton.setBackground(new java.awt.Color(0, 76, 68));
        hotelgoodjRadioButton.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        hotelgoodjRadioButton.setForeground(new java.awt.Color(153, 255, 153));
        hotelgoodjRadioButton.setText("很好");
        hotelgoodjRadioButton.setToolTipText("");
        jPanel1.add(hotelgoodjRadioButton);
        hotelgoodjRadioButton.setBounds(290, 100, 70, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>      
    
    private void returnjButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
        new UserCommentFrame(data).setVisible(true);
    }
    
    private void commitjButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
        new UserCommentFrame(data).setVisible(true);
    }


    // Variables declaration - do not modify
    private userDataVO data;
    private javax.swing.JTextArea commentjTextArea;
    private javax.swing.JButton commitjButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton equipbadjRadioButton;
    private javax.swing.JRadioButton equipcommonjRadioButton;
    private javax.swing.JRadioButton equipgoodjRadioButton;
    private javax.swing.JRadioButton hotelbadjRadioButton;
    private javax.swing.JRadioButton hotelcommonjRadioButton;
    private javax.swing.JRadioButton hotelgoodjRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton returnjButton;
    private javax.swing.JRadioButton roombadjRadioButton;
    private javax.swing.JRadioButton roomcommonjRadioButton;
    private javax.swing.JRadioButton roomgoodjRadioButton;
    // End of variables declaration                   
}
