package UserUI;

import java.rmi.RemoteException; 

import PO.userDataPO;
import RMICLIENT.RMIClient;
import VO.userDataVO;
import transform.VOtoPO;

/**
 *
 * @author ½­»ØêÍ
 */
public class ModifyFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserCommentFrame
     */
    public ModifyFrame(userDataVO data,String str) {
    	this.data = data;
    	this.str = str;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        returnjButton = new javax.swing.JButton();
        modifyjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 180));
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(39, 43, 48));

        jPanel2.setBackground(new java.awt.Color(0, 76, 68));

        jTextField.setText(" ");

        jLabel1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("ÐÞ¸ÄÎª £º");

        returnjButton.setBackground(new java.awt.Color(0, 76, 68));
        returnjButton.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 24)); // NOI18N
        returnjButton.setForeground(new java.awt.Color(153, 255, 153));
        returnjButton.setText("È¡Ïû");
        returnjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	returnjButtonActionPerformed(evt);
            }
        });

        modifyjButton.setBackground(new java.awt.Color(0, 76, 68));
        modifyjButton.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 24)); // NOI18N
        modifyjButton.setForeground(new java.awt.Color(153, 255, 153));
        modifyjButton.setText("È·ÈÏÐÞ¸Ä");
        modifyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	modifyjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(returnjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(247, 247, 247))))
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(modifyjButton)
                    .addContainerGap(470, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(returnjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(257, Short.MAX_VALUE)
                    .addComponent(modifyjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(78, 78, 78)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>  
    
    private void returnjButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
    	this.setVisible(false);
    	new UserInformationFrame(data).setVisible(true);
    }  
    
    private void modifyjButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
    	this.setVisible(false);
    	if(str.equals("name")){
    		data.setUserName(jTextField.getText());
    		DataPO = vtp.TouserDataPO(data);
    	}
    	if(str.equals("phone")){
    		data.setUserTel(jTextField.getText());
    		DataPO = vtp.TouserDataPO(data);
    	}
    	if(str.equals("sex")){
    		data.setUserSex(jTextField.getText());
    		DataPO = vtp.TouserDataPO(data);
    	}
    	try{
    		RMIClient.getBasicDataService().modifyUserData(data.getUserID(), DataPO);
    	}catch(RemoteException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	new UserInformationFrame(data).setVisible(true);
    }  

  

    // Variables declaration - do not modify 
    private userDataVO data;
    private userDataPO DataPO;
    private VOtoPO vtp = new VOtoPO();
    private String str;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField;
    private javax.swing.JButton modifyjButton;
    private javax.swing.JButton returnjButton;
    // End of variables declaration                   
}