package UserUI;

import UI.InputAccountFrame;

/**
 *
 * @author ½­»ØêÍ
 */
public class SignInFailFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignInFailFrame
     */
    public SignInFailFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        returnjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 180));

        jPanel2.setBackground(new java.awt.Color(0, 76, 68));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("  ×¢²áÊ§°Ü");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 120, 30);

        returnjButton.setBackground(new java.awt.Color(0, 76, 68));
        returnjButton.setForeground(new java.awt.Color(153, 255, 153));
        returnjButton.setText(" ·µ»Ø");
        jPanel2.add(returnjButton);
        returnjButton.setBounds(23, 65, 110, 20);
        returnjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	returnjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void returnjButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton returnjButton;
    // End of variables declaration                   
}
