package UserUI;

import VO.userDataVO;

/**
 *
 * @author ½­»ØêÍ
 */
public class UserCommentFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserCommentFrame
     */
    public UserCommentFrame(userDataVO data) {
    	this.data = data;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hotelnamejLabel1 = new javax.swing.JLabel();
        hotelnamejLabel2 = new javax.swing.JLabel();
        hotelnamejLabel3 = new javax.swing.JLabel();
        hotelnamejLabel4 = new javax.swing.JLabel();
        hotelnamejLabel5 = new javax.swing.JLabel();
        costjLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        costjLabel5 = new javax.swing.JLabel();
        costjLabel4 = new javax.swing.JLabel();
        costjLabel3 = new javax.swing.JLabel();
        costjLabel2 = new javax.swing.JLabel();
        commentjButton5 = new javax.swing.JButton();
        commentjButton1 = new javax.swing.JButton();
        commentjButton2 = new javax.swing.JButton();
        commentjButton3 = new javax.swing.JButton();
        commentjButton4 = new javax.swing.JButton();
        returnjButton = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel17.setText("jLabel17");

        jLabel19.setText("jLabel19");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 180));

        jPanel1.setBackground(new java.awt.Color(0, 76, 68));
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 360, 365, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(0, 70, 365, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 140, 365, 10);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(0, 210, 365, 10);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(0, 290, 365, 10);

        jLabel1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("**¾Æµê");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 290, 110, 40);

        jLabel2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("¾ÆµêÃû³Æ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 110, 40);

        jLabel3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("¾ÆµêÃû³Æ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 70, 110, 40);

        jLabel4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("¾ÆµêÃû³Æ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 140, 110, 40);

        jLabel5.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("¾ÆµêÃû³Æ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 210, 110, 40);

        jLabel6.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("¾ÆµêÃû³Æ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 290, 110, 40);

        hotelnamejLabel1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18)); // NOI18N
        hotelnamejLabel1.setForeground(new java.awt.Color(153, 255, 153));
        hotelnamejLabel1.setText("**¾Æµê");
        jPanel1.add(hotelnamejLabel1);
        hotelnamejLabel1.setBounds(100, 0, 110, 40);

        hotelnamejLabel2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18)); // NOI18N
        hotelnamejLabel2.setForeground(new java.awt.Color(153, 255, 153));
        hotelnamejLabel2.setText("**¾Æµê");
        jPanel1.add(hotelnamejLabel2);
        hotelnamejLabel2.setBounds(100, 70, 110, 40);

        hotelnamejLabel3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18)); // NOI18N
        hotelnamejLabel3.setForeground(new java.awt.Color(153, 255, 153));
        hotelnamejLabel3.setText("**¾Æµê");
        jPanel1.add(hotelnamejLabel3);
        hotelnamejLabel3.setBounds(100, 140, 110, 40);

        hotelnamejLabel4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18)); // NOI18N
        hotelnamejLabel4.setForeground(new java.awt.Color(153, 255, 153));
        hotelnamejLabel4.setText("**¾Æµê");
        jPanel1.add(hotelnamejLabel4);
        hotelnamejLabel4.setBounds(100, 210, 110, 40);

        hotelnamejLabel5.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 18)); // NOI18N
        hotelnamejLabel5.setForeground(new java.awt.Color(153, 255, 153));
        hotelnamejLabel5.setText("**¾Æµê");
        jPanel1.add(hotelnamejLabel5);
        hotelnamejLabel5.setBounds(100, 290, 110, 40);

        costjLabel1.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        costjLabel1.setForeground(new java.awt.Color(153, 255, 153));
        costjLabel1.setText("200Ôª");
        jPanel1.add(costjLabel1);
        costjLabel1.setBounds(100, 50, 90, 20);

        jLabel14.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 255, 153));
        jLabel14.setText("Ïû·Ñ½ð¶î");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 50, 90, 20);

        jLabel15.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 255, 153));
        jLabel15.setText("Ïû·Ñ½ð¶î");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 120, 90, 20);

        jLabel16.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 255, 153));
        jLabel16.setText("Ïû·Ñ½ð¶î");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(0, 190, 90, 20);

        jLabel18.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 255, 153));
        jLabel18.setText("Ïû·Ñ½ð¶î");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(0, 270, 90, 20);

        jLabel20.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 255, 153));
        jLabel20.setText("Ïû·Ñ½ð¶î");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(0, 340, 90, 20);

        costjLabel5.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        costjLabel5.setForeground(new java.awt.Color(153, 255, 153));
        costjLabel5.setText("200Ôª");
        jPanel1.add(costjLabel5);
        costjLabel5.setBounds(100, 340, 90, 20);

        costjLabel4.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        costjLabel4.setForeground(new java.awt.Color(153, 255, 153));
        costjLabel4.setText("200Ôª");
        jPanel1.add(costjLabel4);
        costjLabel4.setBounds(100, 270, 90, 20);

        costjLabel3.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        costjLabel3.setForeground(new java.awt.Color(153, 255, 153));
        costjLabel3.setText("200Ôª");
        jPanel1.add(costjLabel3);
        costjLabel3.setBounds(100, 190, 90, 20);

        costjLabel2.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        costjLabel2.setForeground(new java.awt.Color(153, 255, 153));
        costjLabel2.setText("200Ôª");
        jPanel1.add(costjLabel2);
        costjLabel2.setBounds(100, 120, 90, 20);

        commentjButton5.setBackground(new java.awt.Color(0, 76, 68));
        commentjButton5.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        commentjButton5.setForeground(new java.awt.Color(153, 255, 153));
        commentjButton5.setText("ÆÀ¼Û");
        jPanel1.add(commentjButton5);
        commentjButton5.setBounds(260, 330, 100, 30);
        commentjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	commentjButtonActionPerformed(evt);
            }
        });

        commentjButton1.setBackground(new java.awt.Color(0, 76, 68));
        commentjButton1.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        commentjButton1.setForeground(new java.awt.Color(153, 255, 153));
        commentjButton1.setText("ÆÀ¼Û");
        jPanel1.add(commentjButton1);
        commentjButton1.setBounds(263, 40, 100, 30);
        commentjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	commentjButtonActionPerformed(evt);
            }
        });

        commentjButton2.setBackground(new java.awt.Color(0, 76, 68));
        commentjButton2.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        commentjButton2.setForeground(new java.awt.Color(153, 255, 153));
        commentjButton2.setText("ÆÀ¼Û");
        jPanel1.add(commentjButton2);
        commentjButton2.setBounds(260, 110, 100, 30);
        commentjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	commentjButtonActionPerformed(evt);
            }
        });

        commentjButton3.setBackground(new java.awt.Color(0, 76, 68));
        commentjButton3.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        commentjButton3.setForeground(new java.awt.Color(153, 255, 153));
        commentjButton3.setText("ÆÀ¼Û");
        jPanel1.add(commentjButton3);
        commentjButton3.setBounds(260, 180, 100, 30);
        commentjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	commentjButtonActionPerformed(evt);
            }
        });

        commentjButton4.setBackground(new java.awt.Color(0, 76, 68));
        commentjButton4.setFont(new java.awt.Font("ËÎÌå", 0, 18)); // NOI18N
        commentjButton4.setForeground(new java.awt.Color(153, 255, 153));
        commentjButton4.setText("ÆÀ¼Û");
        jPanel1.add(commentjButton4);
        commentjButton4.setBounds(260, 260, 100, 30);
        commentjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	commentjButtonActionPerformed(evt);
            }
        });

        returnjButton.setBackground(new java.awt.Color(0, 76, 68));
        returnjButton.setFont(new java.awt.Font("ËÎÌå", 0, 24)); // NOI18N
        returnjButton.setForeground(new java.awt.Color(153, 255, 153));
        returnjButton.setText("·µ»Ø");
        jPanel1.add(returnjButton);
        returnjButton.setBounds(120, 400, 140, 30);
        returnjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	returnjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>     
    
    private void commentjButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
        new CommentFrame(data).setVisible(true);
    }
    
    private void returnjButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
        new UserMainFrame(data).setVisible(true);
    }

    

    // Variables declaration - do not modify 
    private userDataVO data;
    private javax.swing.JButton commentjButton1;
    private javax.swing.JButton commentjButton2;
    private javax.swing.JButton commentjButton3;
    private javax.swing.JButton commentjButton4;
    private javax.swing.JButton commentjButton5;
    private javax.swing.JLabel costjLabel1;
    private javax.swing.JLabel costjLabel2;
    private javax.swing.JLabel costjLabel3;
    private javax.swing.JLabel costjLabel4;
    private javax.swing.JLabel costjLabel5;
    private javax.swing.JLabel hotelnamejLabel1;
    private javax.swing.JLabel hotelnamejLabel2;
    private javax.swing.JLabel hotelnamejLabel3;
    private javax.swing.JLabel hotelnamejLabel4;
    private javax.swing.JLabel hotelnamejLabel5;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton returnjButton;
    // End of variables declaration                   
}