/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NetworkManagersUI;

/**
 *
 * @author t
 */
public class StaffManageFrame extends javax.swing.JFrame {

    /**
     * Creates new form StaffInformation
     */
    public StaffManageFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        JPanel2 = new javax.swing.JPanel();
        MenberName = new javax.swing.JLabel();
        LoginMember = new javax.swing.JLabel();
        CurrentTime = new javax.swing.JLabel();
        LoginTime = new javax.swing.JLabel();
        MainJPanel = new javax.swing.JPanel();
        StaffManage = new javax.swing.JLabel();
        HotelInformationManage = new javax.swing.JLabel();
        Staff = new javax.swing.JButton();
        Hotel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Network Managers Frame");
        setLocation(new java.awt.Point(380, 180));
        setPreferredSize(new java.awt.Dimension(747, 424));
        setResizable(false);

        JPanel1.setBackground(new java.awt.Color(39, 43, 48));
        JPanel1.setPreferredSize(new java.awt.Dimension(747, 424));

        JPanel2.setBackground(new java.awt.Color(0, 76, 68));

        MenberName.setBackground(new java.awt.Color(255, 255, 255));
        MenberName.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18)); // NOI18N
        MenberName.setForeground(new java.awt.Color(153, 255, 153));
        MenberName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenberName.setText("»À‘±–’√˚");

        LoginMember.setBackground(new java.awt.Color(255, 255, 255));
        LoginMember.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18)); // NOI18N
        LoginMember.setForeground(new java.awt.Color(153, 255, 153));
        LoginMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginMember.setText("µ«¬º»À‘±£∫");

        
        NetworkManagersFrame frame=new NetworkManagersFrame();
        String time=frame.getTime;
        CurrentTime.setBackground(new java.awt.Color(255, 255, 255));
        CurrentTime.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18)); // NOI18N
        CurrentTime.setForeground(new java.awt.Color(153, 255, 153));
        CurrentTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CurrentTime.setText(time);

        LoginTime.setBackground(new java.awt.Color(255, 255, 255));
        LoginTime.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18)); // NOI18N
        LoginTime.setForeground(new java.awt.Color(153, 255, 153));
        LoginTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTime.setText("µ«¬º ±º‰£∫");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(JPanel2);
        JPanel2.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(LoginMember, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenberName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(LoginTime, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginMember, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenberName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginTime, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        MainJPanel.setBackground(new java.awt.Color(0, 76, 68));

        StaffManage.setBackground(new java.awt.Color(0, 76, 68));
        StaffManage.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 18)); // NOI18N
        StaffManage.setForeground(new java.awt.Color(153, 255, 153));
        StaffManage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StaffManage.setText("π§◊˜»À‘±π‹¿Ì£∫");

        HotelInformationManage.setBackground(new java.awt.Color(0, 76, 68));
        HotelInformationManage.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 0, 18)); // NOI18N
        HotelInformationManage.setForeground(new java.awt.Color(153, 255, 153));
        HotelInformationManage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HotelInformationManage.setText("æ∆µÍ–≈œ¢π‹¿Ì£∫");

        Staff.setBackground(new java.awt.Color(0, 76, 68));
        Staff.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18)); // NOI18N
        Staff.setForeground(new java.awt.Color(153, 255, 153));
        Staff.setText("π§◊˜»À‘±");
        Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffActionPerformed(evt);
            }
        });

        Hotel.setBackground(new java.awt.Color(0, 76, 68));
        Hotel.setFont(new java.awt.Font("Œ¢»Ì—≈∫⁄", 1, 18)); // NOI18N
        Hotel.setForeground(new java.awt.Color(153, 255, 153));
        Hotel.setText("æ∆µÍ–≈œ¢");
        Hotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotelInformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(MainJPanel);
        MainJPanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HotelInformationManage, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StaffManage, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Staff, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(Hotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffManage, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Staff, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Hotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HotelInformationManage, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(JPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MainJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void StaffActionPerformed(java.awt.event.ActionEvent evt) {                                      
    	
    	new StaffInformation().setVisible(true);
    }                                     

    private void HotelInformationActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        
    	new HotelInformation().setVisible(true);
    }                                                

   

    // Variables declaration - do not modify                     
    private javax.swing.JButton Hotel;
    private javax.swing.JButton Staff;
    private javax.swing.JLabel StaffManage;
    private javax.swing.JLabel MenberName;
    private javax.swing.JLabel LoginMember;
    private javax.swing.JLabel CurrentTime;
    private javax.swing.JLabel LoginTime;
    private javax.swing.JLabel HotelInformationManage;
    private javax.swing.JPanel MainJPanel;
    private javax.swing.JPanel JPanel1;
    private javax.swing.JPanel JPanel2;
    // End of variables declaration                   
}
